name: Gradle Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run ./gradlew check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # change to match your project

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Gradle check
        run: ./gradlew check
